### ISSUE TITLE
UnicodeEncodeError on Email initialization

### ISSUE THREAD

**Issue by nakamichiworks** [y-bar/netcleanser#7]
https://github.com/y-bar/netcleanser/blob/d72e212c40d7150408410a55769fe44ddcf28da2/netcleanser/email.py#L9

ここに`.encode('ascii')`があるために、メールアドレス候補文字列にascii文字以外が入っていると`Email()`の初期化時に以下のようなエラーが出ます。

```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
```

`.encode('ascii')`は不要なように思えるのですが、こうなっている理由は何かありますか？

**Comment by shinichi-takayanagi** [comment]
https://gist.github.com/neu5ron/66078f804f16f9bda828 これぱくってきたからだな〜
